version: '2.4'
services:
  inspire-validator:
    image: docker.io/pdok/inspire-validator:2021.1
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/validator"]
  inspire-etf-validator:
    build: .
    entrypoint:
      - etf
      - -r
      - /results
      - -e
      - http://inspire-validator:8080/validator
    volumes:
      - ./results:/results
    depends_on:
      inspire-validator:
        condition: service_healthy